"""IR / earnings-presentation analysis (MVP2 Track B, M2.6).

A multimodal LLM reads an investor-relations PDF and produces a structured
summary, cross-referenced against the XBRL-extracted financials. This is an
LLM-judgment artifact (less traceable than the structured extraction) — treated
as a complement to, not a substitute for, the filing-based memo.
"""
from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class PresentationAnalysis(BaseModel):
    pdf_path: str
    ticker: str = ""
    summary: str
    key_messages: List[str] = Field(default_factory=list)
    guidance_and_targets: List[str] = Field(default_factory=list)
    highlighted_risks: List[str] = Field(default_factory=list)
    notable_figures: List[str] = Field(default_factory=list)
    consistency_with_filing: str = ""
    generation_mode: str = ""

    def to_markdown(self) -> str:
        lines: List[str] = []
        lines.append(f"# IR Presentation Analysis — {self.ticker or self.pdf_path}")
        lines.append("")
        lines.append("> ⚠️ Generated by a multimodal LLM reading the IR deck — a summary aid, "
                     "not authoritative; verify against the official filing.")
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append(self.summary)
        for title, items in (
            ("Key Messages", self.key_messages),
            ("Guidance & Medium-term Targets", self.guidance_and_targets),
            ("Risks Highlighted", self.highlighted_risks),
            ("Notable Figures / Charts", self.notable_figures),
        ):
            lines.append("")
            lines.append(f"## {title}")
            lines.append("")
            for it in items:
                lines.append(f"- {it}")
        lines.append("")
        lines.append("## Consistency with the Official Filing")
        lines.append("")
        lines.append(self.consistency_with_filing)
        lines.append("")
        lines.append("---")
        lines.append(f"_Source PDF: {self.pdf_path} — {self.generation_mode}_")
        return "\n".join(lines)
